[package]
name = "ornithd"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
ctrlc.workspace = true
local-model-contract = { path = "../local-model-contract" }
serde_json.workspace = true
